faiss_db:
  collection_name: 'document_portal'

embedding_model:
  provider: 'openai'
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  openai:
    provider: 'openai'
    model_name: 'gpt-4.1'
    temperature: 0
    max_output_tokens: 2048